### ISSUE TITLE
subclassing?

### ISSUE THREAD

**Issue by mla** [forwardever/Forward-Routes#1]
Is it possible to subclass Forward::Routes? It looks like the class name is hard-coded in add_route(), for example.

Would you consider defining those dependencies within methods and/or using $self to call the constructors (in the specific example of add_route())?

**Comment by forwardever** [comment]
@mla what kind of behaviour do you want to customize?

**Comment by mla** [comment]
I wanted to do a work-around for an issue I was having. But I think I found the problem -- I just submitted a pull request to you for it.
